CREATE DATABASE DML;
USE DML;
-- DML COMMONDS ---
-- DML: DATA MANIPULATION LANGUAGE 
--   IT IS HEPLS TO MANIPULATE THE DATA WHICH IS INSERT, DELETE,UPDATE AND RETRIVE THE DATA FROM TABLE 
-- COMMONDS
  -- INSERT
  -- UPDATE
  -- DELETE
  -- SELECT
  
-- INSERT : IT IS HEPS TO INSERT VALUES TO THE TABLE
CREATE TABLE CUSTOMERS_FEEDBACK(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
MOBILE VARCHAR(10),
RATING int
);

-- INSET VALUES 
INSERT INTO CUSTOMERS_FEEDBACK (ID,
NAME,MOBILE,RATING )  VALUES 
( 01, "RANJU", "2344565",4),
( 02, "JAYA", "2344554",5),
( 03, "RAJU", "2345555",3),
( 04, "RANJU", "23222265",2),
( 05, "RANJU", "2346665",4);

DESCRIBE CUSTOMERS_FEEDBACK; -- ONLY WE CAN SEE FORMATE OF TABLE
SELECT * FROM CUSTOMERS_FEEDBACK; -- WE CAN SEE ENTIRE TABLE WITH FIELDS, RECORDS & FORMATE
SHOW TABLES; -- USING THIS WE CAN SEE ALL TABLES WHICH ARE IN MY DATABASE

-- UPDATE : IT WILL HELP TO UPDATE TABLE ( UPDATE 01 ID NUMBER CUSTOMER WANT TO CHANGE RATING 5)
UPDATE CUSTOMERS_FEEDBACK 
SET RATING = 5
WHERE ID = 01;

-- 2 OR MORE RECORDS UPDATE WHIN ONLY ONE ROW
UPDATE CUSTOMERS_FEEDBACK 
SET NAME= "SIMA",RATING=6
WHERE ID =04;

-- UPDATE MULTIPLE VALUES AND MULTIPLE FIELDS
UPDATE CUSTOMERS_FEEDBACK 
SET NAME=case 
     WHEN ID =04 THEN "SITA"
     WHEN ID =05 THEN "MANU"
     END,
     RATING = case
     WHEN ID =04 THEN 8
     WHEN ID =05 THEN 8
     END
WHERE ID IN (04,05);

-- DELETE : TO REMOVE RECORDS FROM A TABLE: it only row wise delete the records not delete column ( column delete is use to alter commond within drop)
DELETE FROM CUSTOMERS_FEEDBACK
WHERE ID = 05;

-- select: HELP TO SEE SPECIFIC FIELD AND RECORDS
SELECT NAME,RATING FROM CUSTOMERS_FEEDBACK;
 
 
 -- TO SELECT ENTIRE TABLE
 SELECT FROM CUSTOMERS_FEEDBACK ;

     






